### PR TITLE
create files and add my_enumerable

### PR DESCRIPTION
**Pull request by tomasesquivelgc**
# In this branch
 - We create an enumerable module to insert into our custom class.
 - We create our custom class and module in different files.
 - We add the test cases in our class file for easy testing

### CODE REVIEW

**Review by zeff96 — COMMENTED** [review]
## STATUS: INVALID CODE REVIEW 🛑 🛑 
Hi @tomasesquivelgc and @waelelsafty07 , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

- [ ] You've submitted a project, but it seems we missed following the project guidelines 📝! According to the project guidelines 📚, we should create a pull request from our feature branch to the main branch. 🌟

- To get things back on track, let's go ahead and close the current pull request ❌, and then open a shiny new pull request 🌈 from our feature branch to the main branch. 🚀

- This will help us ensure that our project aligns perfectly with the guidelines and makes the reviewing process smoother and more enjoyable! 😊✨

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by tomasesquivelgc** [comment]
Hello @zeff96 . Would you kindly point to where exactly that requirement is mentioned? I can't seem to find it on the project documentation. The only thing concerning the requirements is this paragraph which i will attach: 
image
As you can see, the requirements state that We should use correct GitFlow, which we did by not merging into the main branch. We've never had issues of this kind before. Furthermore I can provide evidence of other students who did not have this problem and used the same GitFlow as me. such as this student: 
image
image
I have crossed their names because it's unnecessary to bring them into this.

To add one final comment, I've checked more advanced students and found the same GitFlow that we've used in this project. You can find a prime example here: https://github.com/zeff96/my_enumerable/pull/1

**Comment by ademibowale** [comment]
@tomasesquivelgc @waelelsafty07 please can you check your linters setup you have no rubocop linters setup please check the project guildlines very well also i have left you a message on slack.

**Review by ademibowale — COMMENTED** [review]
Hi @tomasesquivelgc @waelelsafty07 ,

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project,that has no correct ruby robocop linters setup all linters check was not successfully passed, please use this [Template](https://github.com/microverseinc/linters-config/tree/master/html-css-js) to create a professional documentation

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Review by ademibowale — APPROVED** [review]
Hi @tomasesquivelgc @waelelsafty07 , 


Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## To Highlight 💯 
- No linters errors ✔️
-  MyEnumerable module should be included in MyList class  ✔️
- uses require_relative to import MyEnumerable ✔️
- MyList class has an instance variable @list  ✔️
- Descriptive pull request ✔️ 
- Descriptive commit messages ✔️ 
- Good use of Github flow ✔️






- [x]  _Please check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me on( @Adebowale ) in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by zeff96** [comment]
> Hello @zeff96 . Would you kindly point to where exactly that requirement is mentioned? I can't seem to find it on the project documentation. The only thing concerning the requirements is this paragraph which i will attach: image As you can see, the requirements state that We should use correct GitFlow, which we did by not merging into the main branch. We've never had issues of this kind before. Furthermore I can provide evidence of other students who did not have this problem and used the same GitFlow as me. such as this student: image image I have crossed their names because it's unnecessary to bring them into this.
> 
> To add one final comment, I've checked more advanced students and found the same GitFlow that we've used in this project. You can find a prime example here: [zeff96/my_enumerable#1](https://github.com/zeff96/my_enumerable/pull/1)

Sorry for late reply, Kindly check again the screenshot you attached, click on the lick GitHub flow and read it, for clarity, if you are working on a solo project, the correct workflow is GitFlow, If you are working on a group project the correct workflow is GitHub flow and it is clearly stated in your project requirement

**Comment by zeff96** [comment]
- [ ] Here is the link once again to the project requirement [link](https://github.com/microverseinc/curriculum-ruby/blob/main/simple-ruby/create_your_own_enumerable.md), Kindly read it and understand to avoid confusion in the future

- [ ] Kindly also visit this project [guidelines](https://github.com/microverseinc/curriculum-react-redux/blob/main/bookstore/connect_to_api_v2_1.md) and open on the link of the correct workflow, It will help clear the confusion, kindly read the two project requirements, specifically when they talk about opening a pull request

**Pull request merged**
